<?php

namespace Cilantro\MediaBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
    public function getNotNullSources()
    {
        $qb = $this->createQueryBuilder('m');

        $query = $qb->select('m')
            ->where($qb->expr()->isNotNull('m.source'))
            ->getQuery();

        return $query->getResult();
    }
}
