cilantro_admin:
    resource: "@CilantroAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/

cilantro_media:
    resource: "@CilantroMediaBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"