cilantro_admin:
    resource: "@CilantroAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/

cilantro_media:
    resource: "@CilantroMediaBundle/Controller/"
    type:     annotation
    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
