parameters:
#    parameter_name: value

services:
    cilantro.utils:
          class: Cilantro\AdminBundle\Service\UtilsService
          arguments: ['@service_container']

    youtube:
          class: Cilantro\AdminBundle\Service\YoutubeService
          arguments: ['@doctrine', '@service_container']

    log:
          class: Cilantro\AdminBundle\Service\LogService
          arguments: ['@service_container']