parameters:
#    parameter_name: value

services:
    cilantro.utils:
          class: Cilantro\AdminBundle\Service\UtilsService
          arguments: ['@service_container']

    youtube:
          class: Cilantro\AdminBundle\Service\YoutubeService
          arguments: ['@doctrine', '@service_container']

    facebook:
          class: Cilantro\AdminBundle\Service\FacebookService
          arguments: ['@doctrine', '@service_container']

    log:
          class: Cilantro\AdminBundle\Service\LogService
          arguments: ['@service_container']

    app.menu_builder:
          class: Cilantro\MediaBundle\Menu\MenuBuilder
          arguments: ["@knp_menu.factory", '@doctrine']
          tags:
                - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
                - { name: knp_menu.menu_builder, method: createSiteMenu, alias: site }