<?php

namespace Cilantro\AdminBundle\Repository;

/**
 * FacebookVideoListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacebookVideoListRepository extends \Doctrine\ORM\EntityRepository
{
}
