<?php

namespace Cilantro\AdminBundle\Repository;

/**
 * FacebookVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacebookVideoRepository extends \Doctrine\ORM\EntityRepository
{
}
