<?php

namespace Cilantro\AdminBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialNetworkServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
