<?php

namespace Cilantro\AdminBundle\Repository;

/**
 * YoutubeVideoArtistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YoutubeVideoArtistRepository extends \Doctrine\ORM\EntityRepository
{
}
