<?php

namespace Cilantro\AdminBundle\Repository;

/**
 * YoutubeVideoTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YoutubeVideoTagRepository extends \Doctrine\ORM\EntityRepository
{
}
