<?php

namespace Cilantro\AdminBundle\Repository;

/**
 * YoutubeVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YoutubeVideoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOneByCategory()
    {
        $qb = $this->createQueryBuilder('v');

        $query = $qb->select('v')
            ->groupBy('v.category')
            ->where($qb->expr()->isNotNull('v.category'))
            ->getQuery();

        return $query->getResult();
    }

    public function getEpisodes()
    {
        $qb = $this->createQueryBuilder('v');

        $query = $qb->select('v')
            ->groupBy('v.episode')
            ->where($qb->expr()->isNotNull('v.episode'))
            ->orderBy('v.publishedAt', 'desc')
            ->getQuery();

        return $query->getResult();
    }

    public function getMoreEpisodeVideos()
    {
        $qb = $this->createQueryBuilder('v');

        $query = $qb->select('v')
            ->groupBy('v.episode')
            ->where($qb->expr()->isNotNull('v.episode'))
            ->getQuery();

        return $query->getResult();
    }
}