<?php

namespace Cilantro\AdminBundle\Repository;

/**
 * YoutubeVideoCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YoutubeVideoCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
